name: docker-ci-pipeline
on:
  push:
    paths-ignore:
      -'README.md'
      -'CONTRIBUTING.md'
      -'LICENSE'
jobs:
  dockerci-job:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v6
        
      - name: Build Image
        run: docker build -t ${{vars.DOCKER_USERNAME }}/helloworld-demo-python:v1 .
        
      - name: Verify Image
        run: docker images

      - name: Create container
        run: docker run --name python-app -idt -p 8080:8080 ${{vars.DOCKER_USERNAME }}/helloworld-demo-python:v1

      - name: Waiting Time
        run: sleep 20
        
      - name: Check container status
        run: docker ps
      - name: Check output
        run: curl -f http://localhost:8080
        
      - name: Docker Login
        uses: docker/login-action@v3.6.0
        with:
           username: ${{vars.DOCKER_USERNAME }}
           password: ${{secrets.DOCKER_TOKEN }}
           
      - name: Push Image
        run: docker push ${{vars.DOCKER_USERNAME }}/helloworld-demo-python:v1

      - name: Delete the container
        run: docker rm python-app
